"""Add STIX UUIDs and actor-technique mapping

Revision ID: 7a54ac8461f2
Revises: 9fb3edc4b794
Create Date: 2025-09-21 17:51:25.089688

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7a54ac8461f2'
down_revision: str | None = '9fb3edc4b794'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_technique_mappings',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('first_observed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.technique_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'technique_id', 'id')
    )
    op.add_column('actors', sa.Column('stix_uuid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_actors_stix_uuid'), 'actors', ['stix_uuid'], unique=True)
    op.add_column('mitre_tactics', sa.Column('stix_uuid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_mitre_tactics_stix_uuid'), 'mitre_tactics', ['stix_uuid'], unique=True)
    op.add_column('mitre_techniques', sa.Column('stix_uuid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_mitre_techniques_stix_uuid'), 'mitre_techniques', ['stix_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mitre_techniques_stix_uuid'), table_name='mitre_techniques')
    op.drop_column('mitre_techniques', 'stix_uuid')
    op.drop_index(op.f('ix_mitre_tactics_stix_uuid'), table_name='mitre_tactics')
    op.drop_column('mitre_tactics', 'stix_uuid')
    op.drop_index(op.f('ix_actors_stix_uuid'), table_name='actors')
    op.drop_column('actors', 'stix_uuid')
    op.drop_table('actor_technique_mappings')
    # ### end Alembic commands ###
