"""Add structured metadata fields to detections

Revision ID: fce1f36cb2ca
Revises: 22a839cd8fe6
Create Date: 2025-09-21 08:16:40.241707

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'fce1f36cb2ca'
down_revision: str | None = '22a839cd8fe6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
