"""remove log_sources column from detections table

Revision ID: 9a81bfabb414
Revises: fce1f36cb2ca
Create Date: 2025-09-21 08:52:12.487401

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a81bfabb414'
down_revision: str | None = 'fce1f36cb2ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'log_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('log_sources', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
